---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: chimney
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/wayblueorg/sway
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - yalter/niri
        - avengemedia/dms
        - dejan/lazygit
      files:
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
        - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
    install:
      packages:
        - niri
        - dms
        - noctalia-shell
        - neovim
        - ripgrep
        - bat
        - lazygit
        - ranger
        - zsh
        - qt6ct
        - syncthing
        - tailscale
        - mpv
        - iperf3
    remove:
      packages:
        - dunst

  - type: bling
    install:
      - 1password

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
      - scope: user # Also add Flathub user repo, but no user packages

  - type: systemd
    system:
      enabled:
        - tailscaled

  - type: files
    files:
      - source: niri
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
